{{- if empty .Values.additionalServices | not }}
{{- range $i, $s := .Values.additionalServices }}
{{- $serviceName := (required (printf ".Values.additionalServices[%d].name", $i) $s.name) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    {{- include "skipper.labels" . | nindent 4 }}
spec:
  type: {{ $s.type | default "ClusterIP" }}
  {{- required (printf ".Values.additionalServices[%d].ports is required", $i) $s.ports}}
  ports:
    {{- range $j, $p := $s.ports }}
    - name: {{ required (printf ".Values.additionalServices[%d].ports[%d].name" $i $j) $p.name | quote }}
      port: {{ required (printf ".Values.additionalServices[%d].ports[%d].port" $i $j) $p.port }}
      {{- if $p.targetPort }}
      targetPort: {{ $p.targetPort }}
      {{- end }}
      {{- if $p.protocol }}
      protocol: {{ $p.protocol }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "skipper.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}