apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skipper.fullname" . }}
  labels:
    {{- include "skipper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "skipper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/routes: {{ (printf "%s\n%s" (.Values.routes | default "") (.Values.probeRoutes | default "")) | sha256sum }}
        checksum/config: {{ .Values.config | default "" | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "skipper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "skipper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - "skipper"
          - -config-file
          - "/etc/skipper-config/config.yaml"
          {{- if empty .Values.routes | not }}
          - -routes-file
          - "/etc/skipper-routes/routes.eskip"
          {{- end }}
          volumeMounts:
          - name: mainConfig
            mountPath: /etc/skipper-config
          ports:
          - name: service-port
            containerPort: 9090
            protocol: TCP
          livenessProbe:
            {{- toYaml .Vaules.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Vaules.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: mainConfig
          configMap:
            name: {{ include "skipper.fullname" }}-config
