apiVersion: v2
name: skipper
description: A Helm chart for deploying [skipper](https://github.com/zalando/skipper) as cluster internal service proxy
type: application
version: "1.0.0"
appVersion: "0.18.39"
dependencies:
  - name: magda-common
    version: "2.3.1"
    repository: "oci://ghcr.io/magda-io/charts"
