name: Main CI Workflow

on: push

env:
  REPO_NAME: skipper

jobs:
  build-test-docker:
    name: Lint & Test Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Login to GitHub Container Registry
        run: |
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: yarn install

      - run: yarn update-all-charts
      - run: yarn helm-lint

      - name: Check Helm Chart Document
        run: |
          code=0
          yarn helm-docs || code=$?;
          if [ "$code" != "0" ]; then 
            echo "Failed to run helm-docs!";
            exit 1;
          fi;
          code=0
          git ls-files -m | grep -i readme.md || code=$?;
          if [ "$code" == "0" ]; then
            echo -e "Some of helm chart docs are required to be updated using the [helm-docs](https://github.com/norwoodj/helm-docs) tool. \n
            Please run helm-docs (v1.11.3) at project root, review & commit docs changes and push a new commit.";
            exit 1;
          else 
            echo -e "helm docs check passed. helm docs update is not required.";
          fi;
